host: https://applikatoni.shipping-company.com
application: main-web-app
api_token: 4fdd575f-F000-B44R-af1e-ce3e9f75367d
stages:
  staging:
    - FETCH_CODE
    - LINK_CONFIG_FILES
    - PREPARE_ASSETS
    - RESTART_SERVER
  production:
    - QUIET_WORKERS
    - FETCH_CODE
    - LINK_CONFIG_FILES
    - PREPARE_ASSETS
    - RESTART_SERVER
